### PR TITLE
STK fixes

### PR DESCRIPTION
**Pull request by jewatkins**
Looks good to me, thanks Luca

### CODE REVIEW

**Comment by lbertagna** [comment]
Thanks for opening the PR. I forgot I could have forked albany in my personal account, and issue a pr from the fork...

**Comment by jewatkins** [comment]
is this good to push?

**Comment by lbertagna** [comment]
I am still running the testsuite (corePDEs passed). However, given that this was a matter of compilation errors, and given that we don't check output files content in our tests (something we should do at some point), I don't foresee any failure, so we could probably merge right away.

**Comment by jewatkins** [comment]
sounds good thanks

**Comment by mperego** [comment]
thanks @lbertagna and @jewatkins !

**Pull request merged**
