### PR TITLE
Update weaver build

### PR DESCRIPTION
**Pull request by jewatkins**
This only works on a rhel8 node.
```
100% tests passed, 0 tests failed out of 129

Label Time Summary:
Adjoint        = 441.63 sec*proc (8 tests)
Basic          = 234.76 sec*proc (35 tests)
Demo           = 739.63 sec*proc (28 tests)
Epetra         =  10.70 sec*proc (2 tests)
FROSch         =  25.43 sec*proc (2 tests)
Forward        = 1951.76 sec*proc (103 tests)
LandIce        = 1422.39 sec*proc (50 tests)
RegressFail    =   8.01 sec*proc (2 tests)
Serial         = 542.98 sec*proc (13 tests)
Tempus         =  19.45 sec*proc (1 test)
Tpetra         = 2382.70 sec*proc (109 tests)

Total Test time (real) = 2419.65 sec
```

### CODE REVIEW

**Review by ikalash — APPROVED** [review]
I tested this and everything looks good.  I'll go ahead and approve/merge, then make the changes on weaver.

**Comment by jewatkins** [comment]
@ikalash It looks like it didn't find the `NETCDF_C_ROOT` path?
https://sems-cdash-son.sandia.gov/cdash/build/39991/configure

**Comment by jewatkins** [comment]
I think I just needed to update the tpl paths in the ctest script: 5e4cfbe51e90439a0484c5746146e777eabb42c3
This should work now.

**Comment by ikalash** [comment]
Thanks @jewatkins , I just updated the file on weaver in the dir where the tests run.

**Pull request merged**
