### PR TITLE
Fix attaway build

### PR DESCRIPTION
**Pull request by jewatkins**
@ikalash I'm reverting the attaway build to add `-mkl` because the other approach didn't work (maybe an old mkl?). https://github.com/sandialabs/Albany/issues/933

Could you point me to where these files need to be copied?

### CODE REVIEW

**Comment by bartgol** [comment]
It would be helpful if the build scripts used `-DCMAKE_VERBOSE_MAKEFILE=ON`, so we can see the compile line. Alternatively, can we make the build dir have 755 permissions, so we can go in and manually check the flags.txt and link.txt files?

**Comment by jewatkins** [comment]
I agree. These directories should be group readable like on blake/weaver. And executable so everyone can use the final binary.

**Comment by ikalash** [comment]
Sorry about the permissions issue.  THe problem was that permissions were not auto reset to wg-albany after the nightly build, like they are on say the CEE machines.  THe problem has been corrected.  I can add this option as well ```-DCMAKE_VERBOSE_MAKEFILE=ON```.

**Comment by ikalash** [comment]
I just updated the files based on what was in the repo.  THe place the nightlies happen is /projects/albany/nightlyCDash.

**Comment by jewatkins** [comment]
I just merged the fix. The files likely weren't part of the copy. I can do that tomorrow once permissions are autofixed.

**Comment by ikalash** [comment]
I changed the perms manually so you should be able to copy the files.

**Comment by jewatkins** [comment]
Can you try one more time?
`rwx------ 4 ikalash ikalash 4096 Apr 21 14:21 nightlyCDash`
Thanks!

**Comment by ikalash** [comment]
Looks like now there is an issue having to do with Amesos2/superlu: https://sems-cdash-son.sandia.gov/cdash//viewBuildError.php?buildid=47660 .

**Comment by ikalash** [comment]
Also, sorry about the perms, they have been corrected.

**Comment by jewatkins** [comment]
The new files weren't in. I just copied them over so we should be good tomorrow.

**Comment by jewatkins** [comment]
Forget to set group permissions... hopefully tomorrow this is working.

**Pull request merged**
