### PR TITLE
Use camelCase folder naming convention for PyAlbany

### PR DESCRIPTION
**Pull request by kliegeois**

### CODE REVIEW

**Comment by mperego** [comment]
@kliegeois looks good. Thanks@! 
In Albany tests we got rid of the `small`/`large` folders, however we run the large tests only when ALBANY_LARGE_TESTS is defined. We also renamed `LandIce` into `landIce`. So, you could consider doing the same. Also, `inputOutput` might be better than `iO`.

**Comment by kliegeois** [comment]
@mperego that sounds good with me. I will update the PR to be consistent with the rest of the repo.

**Comment by kliegeois** [comment]
(I just checked and the ctest tests using spack passed)

**Review by mperego — APPROVED** [review]
Looks good to me. Thanks!

**Comment by kliegeois** [comment]
Thanks @mperego !

**Pull request merged**
