### PR TITLE
Added parallel orthogonalization method for PyAlbany MultiVectors

### PR DESCRIPTION
**Pull request by thartland**
Added a orthogTpMVecs method that can be accessed from the Python interface of Albany, so that one can orthogonalize distributed MultiVector's.
Tests have been added to test the orthogonalization method.
Utils has been updated that now provides an inner product method for distributed vectors.
Credit should be given to Jennifer A. Loe for providing the majority of the source code as an example.

### CODE REVIEW

**Comment by kliegeois** [comment]
Thanks @thartland for the modifications.

I retried the branch on my workstation.
Before your last commit, all the PyAlbany tests passed.
After the last commit some failed:

```
The following tests FAILED:
	233 - PyAlbany_SteadyHeat (Failed)
	234 - PyAlbany_SteadyHeat_MPI (Failed)
	235 - PyAlbany_Inv_SteadyHeat (Failed)
	236 - PyAlbany_Inv_SteadyHeat_MPI (Timeout)
	237 - PyAlbany_multiple_SteadyHeat (Failed)
	238 - PyAlbany_multiple_SteadyHeat_MPI (Timeout)
Errors while running CTest
```

Do you see the same behavior on your machine(s)?

**Comment by thartland** [comment]
Hello @kliegeois, I just pulled from the forked branch that I am attempting to merge, I did a fresh build (on Blake) and ran the PyAlbany ctests and all passed.

`      Start 229: PyAlbany_ExtremeEvent
 1/12 Test #229: PyAlbany_ExtremeEvent ..............   Passed   11.70 sec
      Start 230: PyAlbany_ExtremeEvent_MPI
 2/12 Test #230: PyAlbany_ExtremeEvent_MPI ..........   Passed    7.42 sec
      Start 231: PyAlbany_IO
 3/12 Test #231: PyAlbany_IO ........................   Passed    3.46 sec
      Start 232: PyAlbany_IO_MPI
 4/12 Test #232: PyAlbany_IO_MPI ....................   Passed    3.19 sec
      Start 233: PyAlbany_SteadyHeat
 5/12 Test #233: PyAlbany_SteadyHeat ................   Passed    6.77 sec
      Start 234: PyAlbany_SteadyHeat_MPI
 6/12 Test #234: PyAlbany_SteadyHeat_MPI ............   Passed    4.89 sec
      Start 235: PyAlbany_Inv_SteadyHeat
 7/12 Test #235: PyAlbany_Inv_SteadyHeat ............   Passed    2.94 sec
      Start 236: PyAlbany_Inv_SteadyHeat_MPI
 8/12 Test #236: PyAlbany_Inv_SteadyHeat_MPI ........   Passed    2.87 sec
      Start 237: PyAlbany_multiple_SteadyHeat
 9/12 Test #237: PyAlbany_multiple_SteadyHeat .......   Passed    2.96 sec
      Start 238: PyAlbany_multiple_SteadyHeat_MPI
10/12 Test #238: PyAlbany_multiple_SteadyHeat_MPI ...   Passed    2.85 sec
      Start 239: PyAlbany_SteadyHeat_StateMap
11/12 Test #239: PyAlbany_SteadyHeat_StateMap .......   Passed    3.44 sec
      Start 240: PyAlbany_SteadyHeat_StateMap_MPI
12/12 Test #240: PyAlbany_SteadyHeat_StateMap_MPI ...   Passed    3.25 sec

100% tests passed, 0 tests failed out of 12

Total Test time (real) =  55.96 sec
`

**Comment by kliegeois** [comment]
Thanks @thartland for the information.
Let me retry once again.

**Comment by thartland** [comment]
@kliegeois, everything is working fine on my end (sorry for the delay, I had to double check something as this is my first time contributing to a project and thought I made a mistake with my usage of git).

      Start 229: PyAlbany_ExtremeEvent
 1/14 Test #229: PyAlbany_ExtremeEvent .......................   Passed    9.53 sec
      Start 230: PyAlbany_ExtremeEvent_MPI
 2/14 Test #230: PyAlbany_ExtremeEvent_MPI ...................   Passed    7.28 sec
      Start 231: PyAlbany_IO
 3/14 Test #231: PyAlbany_IO .................................   Passed    3.17 sec
      Start 232: PyAlbany_IO_MPI
 4/14 Test #232: PyAlbany_IO_MPI .............................   Passed    3.16 sec
      Start 233: PyAlbany_SteadyHeat
 5/14 Test #233: PyAlbany_SteadyHeat .........................   Passed    6.74 sec
      Start 234: PyAlbany_SteadyHeat_MPI
 6/14 Test #234: PyAlbany_SteadyHeat_MPI .....................   Passed    4.93 sec
      Start 235: PyAlbany_Inv_SteadyHeat
 7/14 Test #235: PyAlbany_Inv_SteadyHeat .....................   Passed    3.27 sec
      Start 236: PyAlbany_Inv_SteadyHeat_MPI
 8/14 Test #236: PyAlbany_Inv_SteadyHeat_MPI .................   Passed    2.83 sec
      Start 237: PyAlbany_multiple_SteadyHeat
 9/14 Test #237: PyAlbany_multiple_SteadyHeat ................   Passed    2.93 sec
      Start 238: PyAlbany_multiple_SteadyHeat_MPI
10/14 Test #238: PyAlbany_multiple_SteadyHeat_MPI ............   Passed    2.85 sec
      Start 239: PyAlbany_SteadyHeat_StateMap
11/14 Test #239: PyAlbany_SteadyHeat_StateMap ................   Passed    3.46 sec
      Start 240: PyAlbany_SteadyHeat_StateMap_MPI
12/14 Test #240: PyAlbany_SteadyHeat_StateMap_MPI ............   Passed    3.11 sec
      Start 241: PyAlbany_SteadyHeat_Orthogonalization
13/14 Test #241: PyAlbany_SteadyHeat_Orthogonalization .......   Passed    2.57 sec
      Start 242: PyAlbany_SteadyHeat_Orthogonalization_MPI
14/14 Test #242: PyAlbany_SteadyHeat_Orthogonalization_MPI ...   Passed    2.62 sec

100% tests passed, 0 tests failed out of 14

Total Test time (real) =  58.66 sec

**Comment by kliegeois** [comment]
@thartland, I confirm, it is not working.

The modification of the norm function currently returns the square of the norm (the dot product) and not the norm itself.

Replacing the line by:

```
norm = np.sqrt(inner(distributedVector, distributedVector, comm))
```

solves the issue on my workstation.

**Comment by thartland** [comment]
@kliegeois, my mistake. Thanks for catching that. Things have been updated.

**Review by kliegeois — APPROVED** [review]
It looks good to me, thanks!

**Pull request merged**
