### PR TITLE
Fix intel builds

### PR DESCRIPTION
**Pull request by jewatkins**
This partially fixes https://github.com/sandialabs/Albany/issues/933

@ikalash Go ahead and push this if this looks good to you. You will likely need to change your cee-compute scripts to point to the new `doc/dashboards/cee-compute011.sandia.gov/do-cmake-albany-intel` script instead of `do-cmake-albany`

### CODE REVIEW

**Comment by bartgol** [comment]
This seems suboptimal, in that it forces the albany user to know if the mkl flag was used to build trilinos. This is something that CMake should handle, via target properties.

In FindTPLMKL.cmake I see
```
# Here is a combination of CMake options that worked for me, when
# building and running on Linux, using the single dynamic library
# option with MKL 10.3:
#
# -D BLAS_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" 
# -D BLAS_LIBRARY_NAMES:STRING="mkl_rt" 
# -D LAPACK_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" 
# -D LAPACK_LIBRARY_NAMES:STRING="mkl_rt" 
# -D MKL_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" 
# -D MKL_LIBRARY_NAMES:STRING="mkl_rt" 
# -D MKL_INCLUDE_DIRS:FILEPATH="${MKLROOT}/include" 
```
Maybe we can do the same, and get the mkl flag transferred automatically by cmake targets dependencies?

**Comment by jewatkins** [comment]
I can give that try.

**Comment by jewatkins** [comment]
that seems to work okay and doesn't require albany config changes so we can try that for now, see if any other issues show up.

**Comment by jewatkins** [comment]
I wasn't able to test everything though, it seems some issue with ifpack in trilinos has come up. It will likely show up tomorrow.

**Comment by jewatkins** [comment]
I'm going to push this although we won't see changes until wednesday.

**Comment by ikalash** [comment]
Sounds good.  I was going to ask if you still want me to look at it.  It's fine to skip that part and see what the nightlies say.  Thanks again!

**Comment by ikalash** [comment]
I can take care of this .  Are the new scripts in the repo in the appropriate doc/dashboards folders?

**Comment by jewatkins** [comment]
yes, thanks!

**Comment by ikalash** [comment]
Done.  Hopefully tomorrow things will be fixed.

**Pull request merged**
