### PR TITLE
Add scripts to build MALI on blake

### PR DESCRIPTION
**Pull request by jewatkins**
@mperego this worked with the smoke test. I'll add the changes to nightly testing separately; just wanted to get the build to you sooner.

### CODE REVIEW

**Review by mperego — APPROVED** [review]
These look good. Thanks!

**Comment by mperego** [comment]
@jewatkins Are you using head of master for `scorpio`? This repo: https://github.com/E3SM-Project/scorpio?
 ?

**Comment by jewatkins** [comment]
I used the MALI-Dev/E3SM scorpio module in `externals/scorpio`

**Comment by jewatkins** [comment]
it looks like it points to a version from Dec. 2022 - scorpio-v1.4.1

**Pull request merged**
