### PR TITLE
Only enable ifpack2 if specified

### LINKED ISSUE #935: Failing tests: Ifpack not found
@ikalash @mperego Lots of tests are failing, I think due to https://github.com/trilinos/Trilinos/pull/11739
https://sems-cdash-son.sandia.gov/cdash/test/3398184
```
 Error, the parameter {name="Ifpack Settings",type="ParameterList",value="..."}
 in the parameter (sub)list "Albany Parameters->Piro->NOX->Direction->Newton->Stratimikos Linear Solver->Stratimikos->Preconditioner Types->Ifpack"
 was not found in the list of valid parameters!
 
 The valid parameters and types are:
   {
     "Prec Type" : string = ILUT
     "Overlap" : int = 0
     "half precision" : bool = 0
     "Ifpack2 Settings" : ParameterList = ...
     "VerboseObject" : ParameterList = ...
   }
```
I thought the plan was to get rid of all Epetra/Ifpack tests? What's the status of that?

@bartlettroscoe Is there a simple fix for this or do we basically have to rip out all usage of ifpack?

### PR DESCRIPTION
**Pull request by jewatkins**
fixes #935

@mperego I decided to just focus on "enable ifpack2" since I'm not certain if the others are needed in some other context. I'm still running all tests but everything is passing so far.

### CODE REVIEW

**Comment by jewatkins** [comment]
I'm actually not certain if this is even needed anymore since I started by removing the line and some ifpack2 tests still passed...

**Comment by mperego** [comment]
@jewatkins With this change, is it possible to have other preconditioner listed in the input files? As an example, when doing a Tpetra only build, the Epetra preconditioners are not loaded and if we list Epetra preconditioner in the input files we get an error.

**Comment by jewatkins** [comment]
> @jewatkins With this change, is it possible to have other preconditioners listed in the input files? As an example, when doing a Tpetra only build, the Epetra preconditioners are not loaded and if we list Epetra preconditioners in the input files we get an error.

Yes, that shouldn't matter. It just queries "Preconditioner Type" so it shouldn't matter if you have other preconditioners under "Preconditioner Types".

**Comment by jewatkins** [comment]
all tests pass on cee-intel

**Comment by ikalash** [comment]
I'll need to check that CALI Epetra tests pass also, but that can be done by the nightlies after this is merged.

**Comment by jewatkins** [comment]
I just pushed to see what happens with the dashboard. we can revert if this produces other errors.

**Comment by ikalash** [comment]
Thanks so much @jewatkins !  It can't make things worse... :)

**Comment by mperego** [comment]
> Yes, that shouldn't matter. It just queries "Preconditioner Type" so it shouldn't matter if you have other preconditioners under "Preconditioner Types".

My worry was that if you do not enable Ifpack2, because not selected, then Ifpack2 might not be added to the list of the valid preconditioners, and if you have it in the list it could throw an error. But likely that's not the case if all tests pass.

**Comment by jewatkins** [comment]
Hmm I don't see any valid parameter list that might include Ifpack. Also, I'm not sure I understand stratimikos enough to know what needs to be "enabled" for every run.

**Pull request merged**
