### PR TITLE
Misc fixes to disc unit tests and extruded-mesh related stuff

### PR DESCRIPTION
**Pull request by bartgol**
There are still tests failing, but a good amount are already fixed by these changes. I am hoping to catch the last few by tomorrow.

### CODE REVIEW

**Comment by mperego** [comment]
Can we merge this as well even if there are still a few tests failing?

**Comment by bartgol** [comment]
> Can we merge this as well even if there are still a few tests failing?

Yes, I can do that, if you want. This is the list of tests still failing:

```
The following tests FAILED:
	 60 - landIce_FO_GIS_Humboldt_FluxDiv_FROSch (Failed)
	 65 - landIce_FO_GIS_Humboldt_DepthIntegrated_MueLu (Failed)
	 70 - landIce_FO_GIS_AdjointSensitivity_BasalFriction_FluxDivergence (Failed)
	100 - corePDEs_ExtrudedMesh (Failed)
```

**Comment by mperego** [comment]
If you don't get these fixed today I think it would be good to merge.

B.t.w. it seems that all the landice tests failing involve the computation of Flux Divergence.  Did you change the ordering of DOFs for STK Extruded meshes?

**Comment by bartgol** [comment]
> If you don't get these fixed today I think it would be good to merge.
> 
> B.t.w. it seems that all the landice tests failing involve the computation of Flux Divergence. Did you change the ordering of DOFs for STK Extruded meshes?

No, I don't think so.

**Pull request merged**
